const signUpView = () => {
  const signUpViewContainer = document.createElement('div');
  const divForm = document.createElement('div');
  divForm.setAttribute('id', 'formContainer');
  divForm.className = 'formContainer';
  const logoContainer = document.createElement('div');
  logoContainer.className = 'logoContainer';
  const logoImagen = document.createElement('img');
  logoImagen.className = 'logoImagen';
  logoImagen.src = './images/tutipLogo.png';
  logoContainer.appendChild(logoImagen);

  const wrapper = document.createElement('div');
  wrapper.className = 'wrapper';
  const modalForm = document.createElement('div');
  modalForm.className = 'modalForm';
  const buttonsContainer = document.createElement('div');
  buttonsContainer.className = 'buttonsContainer';
  modalForm.appendChild(buttonsContainer);
  const logInButtonLink = document.createElement('a');
  logInButtonLink.href = '#/logIn';
  const logInButton = document.createElement('button');
  logInButton.className = 'actionButton';
  logInButton.classList.add('logInButton');
  logInButton.innerText = 'Iniciar Sesión';
  logInButtonLink.appendChild(logInButton);
  buttonsContainer.appendChild(logInButtonLink);
  const signUpButton = document.createElement('button');
  signUpButton.className = 'actionButton';
  signUpButton.innerText = 'Registrate';
  signUpButton.classList.add('signUpButton');
  buttonsContainer.appendChild(signUpButton);

  const moveButton = document.createElement('button');
  moveButton.className = 'moveButton';
  moveButton.classList.add('rightButton');
  moveButton.innerText = 'Registrate';
  buttonsContainer.appendChild(moveButton);

  const userForm = document.createElement('div');
  userForm.className = 'userForm';
  const form = document.createElement('form');
  form.className = 'form';
  const inputGroup = document.createElement('div');
  inputGroup.className = 'inputGroup';
  const nameUser = document.createElement('input');
  nameUser.setAttribute('type', 'name');
  nameUser.setAttribute('placeholder', 'Ingresa tu nombre');
  const directionMail = document.createElement('input');
  directionMail.setAttribute('type', 'email');
  directionMail.setAttribute('placeholder', 'Correo');
  const password = document.createElement('input');
  password.setAttribute('type', 'password');
  password.setAttribute('placeholder', 'Contraseña');
  const passwordConfirm = document.createElement('input');
  passwordConfirm.setAttribute('type', 'password');
  passwordConfirm.setAttribute('placeholder', 'Confirma tu contraseña');
  const submitButton = document.createElement('button');
  submitButton.className = 'submitButton';
  submitButton.innerText = 'Registrate';
  inputGroup.appendChild(nameUser);
  inputGroup.appendChild(directionMail);
  inputGroup.appendChild(password);
  inputGroup.appendChild(passwordConfirm);
  form.appendChild(inputGroup);
  form.appendChild(submitButton);
  userForm.appendChild(form);
  const logInText = document.createElement('p');
  logInText.innerText = '¿Ya tienes cuenta?';
  const logInLink = document.createElement('a');
  logInLink.innerText = 'Ingresa aquí';
  logInLink.href = '#/logIn';
  logInText.appendChild(logInLink);

  const footer = document.createElement('p');
  footer.innerText = '©Copyright 2022';
  footer.className = 'footerView';
  wrapper.appendChild(modalForm);
  wrapper.appendChild(footer);
  modalForm.appendChild(userForm);
  signUpViewContainer.appendChild(logoContainer);
  signUpViewContainer.appendChild(wrapper);
  return signUpViewContainer;
};
export default signUpView;
